#!/bin/sh

/bin/hostname hdoip

# Mount filesystems
/bin/mount -t proc proc /proc -o noexec,nosuid,nodev
/bin/mount -t sysfs sysfs /sys -o noexec,nosuid,nodev
/bin/mount -t jffs2 /dev/mtdblock1 /mnt/config

mkdir -p /dev/pts
mount -t devpts devpts /dev/pts -o noexec,nosuid

# For debugging: make kernel messages appear at the console
echo 8 > /proc/sys/kernel/printk

# the default calculated values for these kernel controls are too small for
# an embedded nommu system, so override them.  For more info check out
# - ./Documentation/sysctl/vm.txt
# - ./Documentation/filesystems/proc.txt
#
echo 4096 > /proc/sys/vm/min_free_kbytes
echo 300  > /proc/sys/vm/vfs_cache_pressure

# Network setup
/sbin/ifconfig lo 127.0.0.1
/sbin/route add -net 127.0.0.0 netmask 255.0.0.0 lo
/sbin/modprobe hdoip_ether
/sbin/ifconfig eth0 192.168.1.200 netmask 255.255.255.0 up
# Add route entry for multicast
/sbin/route add -net 224.0.0.0 netmask 224.0.0.0 dev eth0
# Allow multicast/broadcast ping
echo 0 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts

/sbin/modprobe hdoip_core

/bin/cat /etc/motd

/bin/hdoipd /tmp/hdoipd0 /tmp/web &
