/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef COMMANDS_H
#define COMMANDS_H

/* function declarations */
void init_commands(void);

Netsnmp_Node_Handler handle_vrbPlay;
Netsnmp_Node_Handler handle_vrbReady;
Netsnmp_Node_Handler handle_reboot;
Netsnmp_Node_Handler handle_factoryDefault;
Netsnmp_Node_Handler handle_store;
Netsnmp_Node_Handler handle_remoteUpdate;

#endif /* COMMANDS_H */
