/**
 * Note: this file originally auto-generated by mib2c using
 * : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 *
 * @file commands.c
 * Execute commands over SNMP
 *
 * Copyright (C) 2012, Institute of Embedded Systems
 *                     Zurich University of Applied Sciences
 *
 * Author(s):
 *   Lukas Itin <itin@zhaw.ch>
 *
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <fcntl.h>
#include <errno.h>

#include "commands.h"
#include "../../hdoip_daemon/hdoipd_msg.h"
#include "hdoip_common.h"

// MACROS
#define HANDLE_FUNCTION(h_para, function_name, parameter)                     \
int handle_##h_para(netsnmp_mib_handler *handler,                             \
                          netsnmp_handler_registration *reginfo,              \
                          netsnmp_agent_request_info   *reqinfo,              \
                          netsnmp_request_info         *requests){            \
    t_snmp_array arr = {function_name, parameter, ""};                        \
    if (getset_value_generic(&arr, reqinfo->mode, requests) != 0){            \
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode ); \
        return SNMP_ERR_GENERR;}                                              \
    return SNMP_ERR_NOERROR;}                                                 \

#define REGISTER_SCALAR(h_para, parameter)                                    \
netsnmp_register_scalar(                                                      \
    netsnmp_create_handler_registration(parameter, handle_##h_para,           \
    h_para##_oid, OID_LENGTH(h_para##_oid), HANDLER_CAN_RWRITE));             \

// Initializes the commands module
void init_commands(void){
    static oid vrbPlay_oid[] = { 1,3,6,1,4,1,1111,1,4,1 };
    static oid vrbReady_oid[] = { 1,3,6,1,4,1,1111,1,4,2 };
    static oid reboot_oid[] = { 1,3,6,1,4,1,1111,1,4,3 };
    static oid factoryDefault_oid[] = { 1,3,6,1,4,1,1111,1,4,4 };
    static oid store_oid[] = { 1,3,6,1,4,1,1111,1,4,5 };
    static oid remoteUpdate_oid[] = { 1,3,6,1,4,1,1111,1,4,6 };

    DEBUGMSGTL(("commands", "Initializing\n"));

    REGISTER_SCALAR(vrbPlay, "vrb-play")
    REGISTER_SCALAR(vrbReady, "vrb-ready")
    REGISTER_SCALAR(reboot, "reboot")
    REGISTER_SCALAR(factoryDefault, "factory-default")
    REGISTER_SCALAR(store, "store")
    REGISTER_SCALAR(remoteUpdate, "remote-update")
}

/* This functions register the handler for each request
 *
 * @param       1. Name of function, only used for macro to generate function name
 * @param       2. Name of function to call to execute command
 * @param       3. Name of the command to execute
 * @return      error message
 * */
HANDLE_FUNCTION(vrbPlay, HOIC_SW, HOIC_VRB_PLAY)
HANDLE_FUNCTION(vrbReady, HOIC_SW, HOIC_READY)
HANDLE_FUNCTION(reboot, HOIC_SW, HOIC_REBOOT)
HANDLE_FUNCTION(factoryDefault, HOIC_SW, HOIC_FACTORY_DEFAULT)
HANDLE_FUNCTION(store, HOIC_SW, HOIC_STORE_CFG)
HANDLE_FUNCTION(remoteUpdate, HOIC_REMOTE_UP, 0)
