/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 *
 * @file listener.c
 * The parameters set/get here are have a listener. This means if you start
 * a set/get request, the parameters are updated immediately
 *
 * Copyright (C) 2012, Institute of Embedded Systems
 *                     Zurich University of Applied Sciences
 *
 * Author(s):
 *   Lukas Itin <itin@zhaw.ch>
 *
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <fcntl.h>
#include <errno.h>

#include "listener.h"
#include "../../hdoip_daemon/hdoipd_msg.h"
#include "hdoip_common.h"


// MACROS
#define HANDLE_FUNCTION(h_para, parameter)                                    \
int handle_##h_para(netsnmp_mib_handler *handler,                             \
                          netsnmp_handler_registration *reginfo,              \
                          netsnmp_agent_request_info   *reqinfo,              \
                          netsnmp_request_info         *requests){            \
    t_snmp_array arr = {HOIC_GET_SET, 0, parameter};                     \
    if (getset_value_generic(&arr, reqinfo->mode, requests) != 0){            \
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode ); \
        return SNMP_ERR_GENERR;}                                              \
    return SNMP_ERR_NOERROR;}                                                 \

#define REGISTER_SCALAR(h_para, parameter)                                    \
netsnmp_register_scalar(                                                      \
    netsnmp_create_handler_registration(parameter, handle_##h_para,           \
    h_para##_oid, OID_LENGTH(h_para##_oid), HANDLER_CAN_RWRITE));             \

// Initializes the listener module
void init_listener(void){
    static oid systemIp_oid[] = { 1,3,6,1,4,1,1111,1,2,1 };
    static oid systemSubnet_oid[] = { 1,3,6,1,4,1,1111,1,2,2 };
    static oid systemGateway_oid[] = { 1,3,6,1,4,1,1111,1,2,3 };
    static oid systemMac_oid[] = { 1,3,6,1,4,1,1111,1,2,4 };
    static oid modeStart_oid[] = { 1,3,6,1,4,1,1111,1,2,5 };
    static oid modeMedia_oid[] = { 1,3,6,1,4,1,1111,1,2,6 };
    static oid remoteUri_oid[] = { 1,3,6,1,4,1,1111,1,2,7 };
    static oid helloUri_oid[] = { 1,3,6,1,4,1,1111,1,2,8 };
    static oid bandwidth_oid[] = { 1,3,6,1,4,1,1111,1,2,9 };
    static oid networkDelay_oid[] = { 1,3,6,1,4,1,1111,1,2,10 };

    DEBUGMSGTL(("listener", "Initializing\n"));

    REGISTER_SCALAR(systemIp, "system-ip")
    REGISTER_SCALAR(systemSubnet, "system-subnet")
    REGISTER_SCALAR(systemGateway, "system-gateway")
    REGISTER_SCALAR(systemMac, "system-mac")
    REGISTER_SCALAR(modeStart, "mode-start")
    REGISTER_SCALAR(modeMedia, "mode-media")
    REGISTER_SCALAR(remoteUri, "remote-uri")
    REGISTER_SCALAR(helloUri, "hello-uri")
    REGISTER_SCALAR(bandwidth, "bandwidth")
    REGISTER_SCALAR(networkDelay, "network-delay")
}

/* These functions register the handler for each request
 *
 * @param       1. Name of function, only used for macro to generate function name
 * @param       2. Name of the parameter we want to set/get in the registry
 * @return      error message
 **/
HANDLE_FUNCTION(systemIp, "system-ip")
HANDLE_FUNCTION(systemSubnet, "system-subnet")
HANDLE_FUNCTION(systemGateway, "system-gateway")
HANDLE_FUNCTION(systemMac, "system-mac")
HANDLE_FUNCTION(modeStart, "mode-start")
HANDLE_FUNCTION(modeMedia, "mode-media")
HANDLE_FUNCTION(remoteUri, "remote-uri")
HANDLE_FUNCTION(helloUri, "hello-uri")
HANDLE_FUNCTION(bandwidth, "bandwidth")  //Umrechnen
HANDLE_FUNCTION(networkDelay, "network-delay")

