/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef LISTENER_H
#define LISTENER_H

/* function declarations */
void init_listener(void);
Netsnmp_Node_Handler handle_systemIp;
Netsnmp_Node_Handler handle_systemSubnet;
Netsnmp_Node_Handler handle_systemGateway;
Netsnmp_Node_Handler handle_systemMac;
Netsnmp_Node_Handler handle_modeStart;
Netsnmp_Node_Handler handle_modeMedia;
Netsnmp_Node_Handler handle_remoteUri;
Netsnmp_Node_Handler handle_helloUri;
Netsnmp_Node_Handler handle_bandwidth;
Netsnmp_Node_Handler handle_networkDelay;

#endif /* LISTENER_H */
