/**
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 *
 * @file only_registry.c
 * The parameters set here are only written to the registry. If you want to
 * activate them, store the registry and restart the system
 *
 * Copyright (C) 2012, Institute of Embedded Systems
 *                     Zurich University of Applied Sciences
 *
 * Author(s):
 *   Lukas Itin <itin@zhaw.ch>
 *
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <fcntl.h>
#include <errno.h>

#include "only_registry.h"
#include "../../hdoip_daemon/hdoipd_msg.h"
#include "hdoip_common.h"

// MACROS
#define HANDLE_FUNCTION(h_para, parameter)                                    \
int handle_##h_para(netsnmp_mib_handler *handler,                             \
                          netsnmp_handler_registration *reginfo,              \
                          netsnmp_agent_request_info   *reqinfo,              \
                          netsnmp_request_info         *requests){            \
    t_snmp_array arr = {HOIC_GET_SET, 0, parameter};                     \
    if (getset_value_generic(&arr, reqinfo->mode, requests) != 0){            \
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode ); \
        return SNMP_ERR_GENERR;}                                              \
    return SNMP_ERR_NOERROR;}                                                 \

#define REGISTER_SCALAR(h_para, parameter)                                    \
netsnmp_register_scalar(                                                      \
    netsnmp_create_handler_registration(parameter, handle_##h_para,           \
    h_para##_oid, OID_LENGTH(h_para##_oid), HANDLER_CAN_RWRITE));             \

// Initializes the only_registry module
void init_only_registry(void){
    static oid audioPort_oid[] = { 1,3,6,1,4,1,1111,1,3,1 };
    static oid videoPort_oid[] = { 1,3,6,1,4,1,1111,1,3,2 };
    static oid rscpServerPort_oid[] = { 1,3,6,1,4,1,1111,1,3,3 };
    static oid hdcpForce_oid[] = { 1,3,6,1,4,1,1111,1,3,4 };
    static oid networkAlive_oid[] = { 1,3,6,1,4,1,1111,1,3,5 };
    static oid networkTimeout_oid[] = { 1,3,6,1,4,1,1111,1,3,6 };

    DEBUGMSGTL(("only_registry", "Initializing\n"));

    REGISTER_SCALAR(audioPort, "audio-port")
    REGISTER_SCALAR(videoPort, "video-port")
    REGISTER_SCALAR(rscpServerPort, "rscp-server-port")
    REGISTER_SCALAR(hdcpForce, "hdcp-force")
    REGISTER_SCALAR(networkAlive, "network-alive")
    REGISTER_SCALAR(networkTimeout, "network-timeout")
}

/* These functions register the handler for each request
 *
 * @param       1. Name of function, only used for macro to generate function name
 * @param       2. Name of the parameter we want to set/get in the registry
 * @return      error message
 * */
HANDLE_FUNCTION(audioPort, "audio-port")
HANDLE_FUNCTION(videoPort, "video-port")
HANDLE_FUNCTION(rscpServerPort, "rscp-server-port")
HANDLE_FUNCTION(hdcpForce, "hdcp-force")
HANDLE_FUNCTION(networkAlive, "network-alive")
HANDLE_FUNCTION(networkTimeout, "network-timeout")

