/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef ONLY_REGISTRY_H
#define ONLY_REGISTRY_H

/* function declarations */
void init_only_registry(void);
Netsnmp_Node_Handler handle_audioPort;
Netsnmp_Node_Handler handle_videoPort;
Netsnmp_Node_Handler handle_rscpServerPort;
Netsnmp_Node_Handler handle_hdcpForce;
Netsnmp_Node_Handler handle_networkAlive;
Netsnmp_Node_Handler handle_networkTimeout;

#endif /* ONLY_REGISTRY_H */
