/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
 
#ifndef STATUS_H
#define STATUS_H

/* function declarations */
void init_status(void);
Netsnmp_Node_Handler handle_systemState;
Netsnmp_Node_Handler handle_daemonState;
Netsnmp_Node_Handler handle_daemonVtbState;
Netsnmp_Node_Handler handle_daemonVrbState;
Netsnmp_Node_Handler handle_ethStatus;
Netsnmp_Node_Handler handle_vsoStatus;
Netsnmp_Node_Handler handle_vioStatus;
Netsnmp_Node_Handler handle_asoStatus;
Netsnmp_Node_Handler handle_streamState;
Netsnmp_Node_Handler handle_multicast;
Netsnmp_Node_Handler handle_hdcpStatus;
Netsnmp_Node_Handler handle_serialNumber;
Netsnmp_Node_Handler handle_systemUpdate;

Netsnmp_Node_Handler handle_sysDescr;
Netsnmp_Node_Handler handle_sysObjectId;
Netsnmp_Node_Handler handle_sysUpTime;


Netsnmp_Node_Handler handle_ifNumber;
Netsnmp_Node_Handler handle_ifIndex1;
Netsnmp_Node_Handler handle_ifDescr1;
Netsnmp_Node_Handler handle_ifPhysAddress1;
Netsnmp_Node_Handler handle_ifIndex2;
Netsnmp_Node_Handler handle_ifDescr2;
Netsnmp_Node_Handler handle_ifPhysAddress2;

Netsnmp_Node_Handler handle_ipAdEntAddr;
Netsnmp_Node_Handler handle_ipAdEntNetMask;
Netsnmp_Node_Handler handle_ipAdEntBcastAddr;


#endif /* STATUS_H */
