/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 *
 * @file status.c
 * These are status parameters. They are read only.
 *
 * Copyright (C) 2012, Institute of Embedded Systems
 *                     Zurich University of Applied Sciences
 *
 * Author(s):
 *   Lukas Itin <itin@zhaw.ch>
 *
 */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <fcntl.h>
#include <errno.h>

#include "status.h"
#include "../../hdoip_daemon/hdoipd_msg.h"
#include "hdoip_common.h"


// MACROS
#define HANDLE_FUNCTION(h_para, parameter)                                    \
int handle_##h_para(netsnmp_mib_handler *handler,                             \
                          netsnmp_handler_registration *reginfo,              \
                          netsnmp_agent_request_info   *reqinfo,              \
                          netsnmp_request_info         *requests){            \
    t_snmp_array arr = {HOIC_GET_R_ONLY, 0, parameter};                       \
	if (getset_value_generic(&arr, reqinfo->mode, requests) != 0){            \
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode ); \
        return SNMP_ERR_GENERR;}                                              \
    return SNMP_ERR_NOERROR;}                                                 \

#define REGISTER_SCALAR(h_para, parameter)                                    \
netsnmp_register_scalar(                                                      \
    netsnmp_create_handler_registration(parameter, handle_##h_para,           \
    h_para##_oid, OID_LENGTH(h_para##_oid), HANDLER_CAN_RWRITE));             \

// Initializes the status module
void init_status(void){
    static oid systemState_oid[] = { 1,3,6,1,4,1,1111,1,1,1 };
    static oid daemonState_oid[] = { 1,3,6,1,4,1,1111,1,1,2 };
    static oid daemonVtbState_oid[] = { 1,3,6,1,4,1,1111,1,1,3 };
    static oid daemonVrbState_oid[] = { 1,3,6,1,4,1,1111,1,1,4 };
    static oid ethStatus_oid[] = { 1,3,6,1,4,1,1111,1,1,5 };
    static oid vsoStatus_oid[] = { 1,3,6,1,4,1,1111,1,1,6 };
    static oid vioStatus_oid[] = { 1,3,6,1,4,1,1111,1,1,7 };
    static oid asoStatus_oid[] = { 1,3,6,1,4,1,1111,1,1,8 };
    static oid streamState_oid[] = { 1,3,6,1,4,1,1111,1,1,9 };
    static oid multicast_oid[] = { 1,3,6,1,4,1,1111,1,1,10 };
    static oid hdcpStatus_oid[] = { 1,3,6,1,4,1,1111,1,1,11 };
    static oid serialNumber_oid[] = { 1,3,6,1,4,1,1111,1,1,12 };
    static oid systemUpdate_oid[] = { 1,3,6,1,4,1,1111,1,1,13 };

    static oid sysDescr_oid[] = {1,3,6,1,2,1,1,1};
    static oid sysObjectId_oid[] = {1,3,6,1,2,1,1,2};
    static oid sysUpTime_oid[] = {1,3,6,1,2,1,1,3};

    static oid ifNumber_oid[] = 	  {1,3,6,1,2,1,2,1};
    static oid ifIndex1_oid[] =       {1,3,6,1,2,1,2,2,1,1,1};
    static oid ifDescr1_oid[] =       {1,3,6,1,2,1,2,2,1,2,1};
    static oid ifPhysAddress1_oid[] = {1,3,6,1,2,1,2,2,1,6,1};
    static oid ifIndex2_oid[] =       {1,3,6,1,2,1,2,2,1,1,2};
    static oid ifDescr2_oid[] =       {1,3,6,1,2,1,2,2,1,2,2};
    static oid ifPhysAddress2_oid[] = {1,3,6,1,2,1,2,2,1,6,2};

    static oid ipAdEntAddr_oid[] = {1,3,6,1,2,1,4,20,1,1};
    static oid ipAdEntNetMask_oid[] = {1,3,6,1,2,1,4,20,1,3};
    static oid ipAdEntBcastAddr_oid[] = {1,3,6,1,2,1,4,20,1,4};


    DEBUGMSGTL(("status", "Initializing\n"));

    REGISTER_SCALAR(systemState, "systemState")
    REGISTER_SCALAR(daemonState, "daemonState")
    REGISTER_SCALAR(daemonVtbState, "daemonVtbState")
    REGISTER_SCALAR(daemonVrbState, "daemonVrbState")
    REGISTER_SCALAR(ethStatus, "ethStatus")
    REGISTER_SCALAR(vsoStatus, "vsoStatus")
    REGISTER_SCALAR(vioStatus, "vioStatus")
    REGISTER_SCALAR(asoStatus, "asoStatus")
    REGISTER_SCALAR(streamState, "streamState")
    REGISTER_SCALAR(multicast, "multicast")
    REGISTER_SCALAR(hdcpStatus, "hdcpStatus")
    REGISTER_SCALAR(serialNumber, "serialNumber")
    REGISTER_SCALAR(systemUpdate, "systemUpdate")

    REGISTER_SCALAR(sysDescr,"sysDescr");
    REGISTER_SCALAR(sysObjectId,"sysObjectId");
    REGISTER_SCALAR(sysUpTime,"sysUpTime");

    REGISTER_SCALAR(ifNumber,"ifNumber");
    REGISTER_SCALAR(ifIndex1,"ifIndex1");
    REGISTER_SCALAR(ifDescr1,"ifDescr1");
    REGISTER_SCALAR(ifPhysAddress1,"ifPhysAddress1");
    REGISTER_SCALAR(ifIndex2,"ifIndex2");
    REGISTER_SCALAR(ifDescr2,"ifDescr2");
    REGISTER_SCALAR(ifPhysAddress2,"ifPhysAddress2");

    REGISTER_SCALAR(ipAdEntAddr,"ipAdEntAddr");
    REGISTER_SCALAR(ipAdEntNetMask,"ipAdEntNetMask");
    REGISTER_SCALAR(ipAdEntBcastAddr,"ipAdEntBcastAddr");


}

/* These functions register the handler for each request
 *
 * @param      1. Name of function, only used for macro to generate function name
 * @param      2. Name of the parameter we want to read
 * @return     error message
 * */
HANDLE_FUNCTION(systemState, "system-state")
HANDLE_FUNCTION(daemonState, "daemon-state")
HANDLE_FUNCTION(daemonVtbState, "daemon-vtb-state")
HANDLE_FUNCTION(daemonVrbState, "daemon-vrb-state")
HANDLE_FUNCTION(ethStatus, "eth-status")
HANDLE_FUNCTION(vsoStatus, "vso-status")
HANDLE_FUNCTION(vioStatus, "vio-status")
HANDLE_FUNCTION(asoStatus, "aso-status")
HANDLE_FUNCTION(streamState, "stream-state")
HANDLE_FUNCTION(multicast, "multicast")
HANDLE_FUNCTION(hdcpStatus, "hdcp-status")
HANDLE_FUNCTION(serialNumber, "serial-number")
HANDLE_FUNCTION(systemUpdate, "system-update")

HANDLE_FUNCTION(sysDescr,"sysDescr")
HANDLE_FUNCTION(sysObjectId,"sysObjectId")
HANDLE_FUNCTION(sysUpTime,"sysUpTime")

HANDLE_FUNCTION(ifNumber,"ifNumber")
HANDLE_FUNCTION(ifDescr1,"ifDescr1")
HANDLE_FUNCTION(ifIndex1,"ifIndex1")
HANDLE_FUNCTION(ifPhysAddress1,"ifPhysAddress1")
HANDLE_FUNCTION(ifDescr2,"ifDescr2")
HANDLE_FUNCTION(ifIndex2,"ifIndex2")
HANDLE_FUNCTION(ifPhysAddress2,"ifPhysAddress2")

HANDLE_FUNCTION(ipAdEntAddr,"ipAdEntAddr")
HANDLE_FUNCTION(ipAdEntNetMask,"ipAdEntNetMask")
HANDLE_FUNCTION(ipAdEntBcastAddr,"ipAdEntBcastAddr")


