/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <fcntl.h>
#include <errno.h>
#include "listener.h"
#include "hdoipd_msgg.h"


#define FIFO_NODEC       "/tmp/hdoipd0.cmd"
#define FIFO_NODER       "/tmp/hdoipd0.rsp"

/** Initializes the listener module */
void
init_listener(void)
{
    static oid systemIp_oid[] = { 1,3,6,1,4,1,1111,1,2,1 };
    static oid systemSubnet_oid[] = { 1,3,6,1,4,1,1111,1,2,2 };
    static oid systemGateway_oid[] = { 1,3,6,1,4,1,1111,1,2,3 };
    static oid systemMac_oid[] = { 1,3,6,1,4,1,1111,1,2,4 };
    static oid modeStart_oid[] = { 1,3,6,1,4,1,1111,1,2,5 };
    static oid modeMedia_oid[] = { 1,3,6,1,4,1,1111,1,2,6 };
    static oid remoteUri_oid[] = { 1,3,6,1,4,1,1111,1,2,7 };
    static oid helloUri_oid[] = { 1,3,6,1,4,1,1111,1,2,8 };
    static oid bandwidth_oid[] = { 1,3,6,1,4,1,1111,1,2,9 };
    static oid networkDelay_oid[] = { 1,3,6,1,4,1,1111,1,2,10 };

  DEBUGMSGTL(("listener", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("system-ip", handle_systemIp,
                               systemIp_oid, OID_LENGTH(systemIp_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("system-subnet", handle_systemSubnet,
                               systemSubnet_oid, OID_LENGTH(systemSubnet_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("system-gateway", handle_systemGateway,
                               systemGateway_oid, OID_LENGTH(systemGateway_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("system-mac", handle_systemMac,
                               systemMac_oid, OID_LENGTH(systemMac_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("mode-start", handle_modeStart,
                               modeStart_oid, OID_LENGTH(modeStart_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("mode-media", handle_modeMedia,
                               modeMedia_oid, OID_LENGTH(modeMedia_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("remote-uri", handle_remoteUri,
                               remoteUri_oid, OID_LENGTH(remoteUri_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("hello-uri", handle_helloUri,
                               helloUri_oid, OID_LENGTH(helloUri_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("bandwidth", handle_bandwidth,
                               bandwidth_oid, OID_LENGTH(bandwidth_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("network-delay", handle_networkDelay,
                               networkDelay_oid, OID_LENGTH(networkDelay_oid),
                               HANDLER_CAN_RWRITE
        ));
}

// get and set value generic function ******************************************
int getset_value_generic(char* para, int mode, netsnmp_request_info *requests){

    int fd = -1, fdr = -1, ret;
    char* s;
    
    // open pipe to hdoipd and check if it was successful
    fd = open(FIFO_NODEC, O_RDWR, 0600); 
    if(fd == -1) {
        snmp_log(LOG_ERR, "Failed to open (fd) %s: %s \n", FIFO_NODEC, strerror(errno));
        return -1;
    }
    
    // open pipe to hdoipd and check if it was successful
    fdr = open(FIFO_NODER, O_RDWR, 0600);
    if(fdr == -1) {
        snmp_log(LOG_ERR, "Failed to open (fdr) %s: %s \n", FIFO_NODEC, strerror(errno));
        close(fd); //close the previous pipe
        return -1;
    }
    
    switch(mode) {
        case MODE_GET:     
            s = hoic_get_param(fd, fdr, para);
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, (u_char *)s, strlen((char *)s));
            free(s);
            break;
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_OCTET_STR);
            if ( ret != SNMP_ERR_NOERROR ) {
               // netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;
        case MODE_SET_RESERVE2:
            break;
        case MODE_SET_FREE:
            break;
        case MODE_SET_ACTION:
			(void)snmp_log(LOG_ERR, "HERE WE ARE!\n");
			(void)snmp_log(LOG_ERR, "VALUE: %s \n", requests->requestvb->val.string);
			
			hoic_set_param(fd, para, requests->requestvb->val.string);
            //if (/* XXX: error? */) {
            //    netsnmp_set_request_error(reqinfo, requests, /* some error */);
            //}
            break;
        case MODE_SET_COMMIT:
            break;
        case MODE_SET_UNDO:
            break;
        default:
            // we should never get here, so this is a really bad error
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_systemState\n", mode );
            close(fd);
            close(fdr);
            return -1;
    }
    
    close(fd);
    close(fdr);

    return 0;
}


// get and set system IP *******************************************************
int handle_systemIp(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "system-ip"; 
    
    if (getset_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set system subnet ***************************************************
int handle_systemSubnet(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "system-subnet"; 
    
    if (getset_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set system gateway **************************************************
int handle_systemGateway(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "system-gateway"; 
    
    if (getset_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set system mac ******************************************************
int handle_systemMac(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "system-mac"; 
    
    if (getset_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set mode start ******************************************************
int handle_modeStart(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "mode-start"; 
    
    if (getset_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set mode media ******************************************************
int handle_modeMedia(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "mode-media"; 
    
    if (getset_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set remote uri ******************************************************
int handle_remoteUri(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "remote-uri"; 
    
    if (getset_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set hello uri *******************************************************
int handle_helloUri(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "hello-uri"; 
    
    if (getset_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set bandwidth *******************************************************
int handle_bandwidth(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "bandwidth"; 
    
    if (getset_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set network delay ***************************************************
int handle_networkDelay(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "network-delay"; 
    
    if (getset_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
