/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */
#ifndef ONLY_REGISTRY_H
#define ONLY_REGISTRY_H

/* function declarations */
void init_only_registry(void);
Netsnmp_Node_Handler handle_advcntMin;
Netsnmp_Node_Handler handle_amxHelloMsg;
Netsnmp_Node_Handler handle_audioPort;
Netsnmp_Node_Handler handle_compress;
Netsnmp_Node_Handler handle_configVersion;
Netsnmp_Node_Handler handle_hdcpForce;
Netsnmp_Node_Handler handle_modeSync;
Netsnmp_Node_Handler handle_networkAlive;
Netsnmp_Node_Handler handle_networkTimeout;
Netsnmp_Node_Handler handle_rscpServerPort;
Netsnmp_Node_Handler handle_serialNumber;
Netsnmp_Node_Handler handle_syncTarget;
Netsnmp_Node_Handler handle_systemCmd;
Netsnmp_Node_Handler handle_systemDevCaption;
Netsnmp_Node_Handler handle_systemIfname;
Netsnmp_Node_Handler handle_videoPort;
Netsnmp_Node_Handler handle_webAuthEn;
Netsnmp_Node_Handler handle_webLang;
Netsnmp_Node_Handler handle_webUser;

#endif /* ONLY_REGISTRY_H */
