/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <fcntl.h>
#include <errno.h>
#include "only_registry.h"
#include "listener.h"
#include "hdoipd_msgg.h"


#define FIFO_NODEC       "/tmp/hdoipd0.cmd"
#define FIFO_NODER       "/tmp/hdoipd0.rsp"

/** Initializes the only_registry module */
void
init_only_registry(void)
{
    static oid advcntMin_oid[] = { 1,3,6,1,4,1,1111,1,3,1 };
    static oid amxHelloMsg_oid[] = { 1,3,6,1,4,1,1111,1,3,2 };
    static oid audioPort_oid[] = { 1,3,6,1,4,1,1111,1,3,3 };
    static oid compress_oid[] = { 1,3,6,1,4,1,1111,1,3,4 };
    static oid configVersion_oid[] = { 1,3,6,1,4,1,1111,1,3,5 };
    static oid hdcpForce_oid[] = { 1,3,6,1,4,1,1111,1,3,6 };
    static oid modeSync_oid[] = { 1,3,6,1,4,1,1111,1,3,7 };
    static oid networkAlive_oid[] = { 1,3,6,1,4,1,1111,1,3,8 };
    static oid networkTimeout_oid[] = { 1,3,6,1,4,1,1111,1,3,9 };
    static oid rscpServerPort_oid[] = { 1,3,6,1,4,1,1111,1,3,10 };
    static oid serialNumber_oid[] = { 1,3,6,1,4,1,1111,1,3,11 };
    static oid syncTarget_oid[] = { 1,3,6,1,4,1,1111,1,3,12 };
    static oid systemCmd_oid[] = { 1,3,6,1,4,1,1111,1,3,13 };
    static oid systemDevCaption_oid[] = { 1,3,6,1,4,1,1111,1,3,14 };
    static oid systemIfname_oid[] = { 1,3,6,1,4,1,1111,1,3,15 };
    static oid videoPort_oid[] = { 1,3,6,1,4,1,1111,1,3,16 };
    static oid webAuthEn_oid[] = { 1,3,6,1,4,1,1111,1,3,17 };
    static oid webLang_oid[] = { 1,3,6,1,4,1,1111,1,3,18 };
    static oid webUser_oid[] = { 1,3,6,1,4,1,1111,1,3,20 };

  DEBUGMSGTL(("only_registry", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("advcnt-min", handle_advcntMin,
                               advcntMin_oid, OID_LENGTH(advcntMin_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("amx-hello-msg", handle_amxHelloMsg,
                               amxHelloMsg_oid, OID_LENGTH(amxHelloMsg_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("audio-port", handle_audioPort,
                               audioPort_oid, OID_LENGTH(audioPort_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("compress", handle_compress,
                               compress_oid, OID_LENGTH(compress_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("config-version", handle_configVersion,
                               configVersion_oid, OID_LENGTH(configVersion_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("hdcp-force", handle_hdcpForce,
                               hdcpForce_oid, OID_LENGTH(hdcpForce_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("mode-sync", handle_modeSync,
                               modeSync_oid, OID_LENGTH(modeSync_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("network-alive", handle_networkAlive,
                               networkAlive_oid, OID_LENGTH(networkAlive_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("network-timeout", handle_networkTimeout,
                               networkTimeout_oid, OID_LENGTH(networkTimeout_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("rscp-server-port", handle_rscpServerPort,
                               rscpServerPort_oid, OID_LENGTH(rscpServerPort_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("serial-number", handle_serialNumber,
                               serialNumber_oid, OID_LENGTH(serialNumber_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("sync-target", handle_syncTarget,
                               syncTarget_oid, OID_LENGTH(syncTarget_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("system-cmd", handle_systemCmd,
                               systemCmd_oid, OID_LENGTH(systemCmd_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("system-dev-caption", handle_systemDevCaption,
                               systemDevCaption_oid, OID_LENGTH(systemDevCaption_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("system-ifname", handle_systemIfname,
                               systemIfname_oid, OID_LENGTH(systemIfname_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("video-port", handle_videoPort,
                               videoPort_oid, OID_LENGTH(videoPort_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("web-auth-en", handle_webAuthEn,
                               webAuthEn_oid, OID_LENGTH(webAuthEn_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("web-lang", handle_webLang,
                               webLang_oid, OID_LENGTH(webLang_oid),
                               HANDLER_CAN_RWRITE
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("web-user", handle_webUser,
                               webUser_oid, OID_LENGTH(webUser_oid),
                               HANDLER_CAN_RWRITE
        ));
}

// get and set value generic function ******************************************
int getset_value_genericc(char* para, int mode, netsnmp_request_info *requests){

    int fd = -1, fdr = -1, ret;
    char* s;
    
    // open pipe to hdoipd and check if it was successful
    fd = open(FIFO_NODEC, O_RDWR, 0600); 
    if(fd == -1) {
        snmp_log(LOG_ERR, "Failed to open (fd) %s: %s \n", FIFO_NODEC, strerror(errno));
        return -1;
    }
    
    // open pipe to hdoipd and check if it was successful
    fdr = open(FIFO_NODER, O_RDWR, 0600);
    if(fdr == -1) {
        snmp_log(LOG_ERR, "Failed to open (fdr) %s: %s \n", FIFO_NODEC, strerror(errno));
        close(fd); //close the previous pipe
        return -1;
    }
    
    switch(mode) {
        case MODE_GET:     
            s = hoic_get_param(fd, fdr, para);
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, (u_char *)s, strlen((char *)s));
            free(s);
            break;
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_OCTET_STR);
            if ( ret != SNMP_ERR_NOERROR ) {
               // netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;
        case MODE_SET_RESERVE2:
            break;
        case MODE_SET_FREE:
            break;
        case MODE_SET_ACTION:
			(void)snmp_log(LOG_ERR, "HERE WE ARE!\n");
			(void)snmp_log(LOG_ERR, "VALUE: %s \n", requests->requestvb->val.string);
			
			hoic_set_param(fd, para, requests->requestvb->val.string);
            //if (/* XXX: error? */) {
            //    netsnmp_set_request_error(reqinfo, requests, /* some error */);
            //}
            break;
        case MODE_SET_COMMIT:
            break;
        case MODE_SET_UNDO:
            break;
        default:
            // we should never get here, so this is a really bad error
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_systemState\n", mode );
            close(fd);
            close(fdr);
            return -1;
    }
    
    close(fd);
    close(fdr);

    return 0;
}

// get and set advcnt-min ******************************************************
int handle_advcntMin(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "advcnt-min"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set amx-hello-msg ***************************************************
int handle_amxHelloMsg(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "amx-hello-msg"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set audio-port ******************************************************
int handle_audioPort(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "audio-port"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set compress ********************************************************
int handle_compress(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "compress"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set config-version **************************************************
int handle_configVersion(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "config-version"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set hdcp force ******************************************************
int handle_hdcpForce(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "hdcp-force"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set mode sync *******************************************************
int handle_modeSync(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "mode-sync"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set network alive ***************************************************
int handle_networkAlive(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "network-alive"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set network timeout *************************************************
int handle_networkTimeout(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "network-timeout"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set rscp-server-port ************************************************
int handle_rscpServerPort(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "rscp-server-port"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set serial number ***************************************************
int handle_serialNumber(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "serial-number"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set sync target *****************************************************
int handle_syncTarget(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "sync-target"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set system cmd ******************************************************
int handle_systemCmd(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "system-cmd"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set system-dev-caption **********************************************
int handle_systemDevCaption(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "system-dev-caption"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set system-ifname *************************************************** 
int handle_systemIfname(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "system-ifname"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set video port ******************************************************
int handle_videoPort(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "video-port"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set web auth en *****************************************************
int handle_webAuthEn(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "web-auth-en"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set web lang ********************************************************
int handle_webLang(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "web-lang"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get and set web user ********************************************************
int handle_webUser(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "web-user"; 
    
    if (getset_value_genericc(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get/set parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}
