/*
 * Note: this file originally auto-generated by mib2c using
 *        : mib2c.scalar.conf 11805 2005-01-07 09:37:18Z dts12 $
 * Prepares the miscellaneous scalars to be accessed via SNMP
 *
 * Copyright (C) 2012, Institute of Embedded Systems
 *                     Zurich University of Applied Sciences
 *
 * Author(s):
 *   Lukas Itin <itin@zhaw.ch>
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include <fcntl.h>
#include "status.h"
#include <errno.h>

//#include "hdoip_cli.h"
//#include "hdoip_lib.h"
#include "hdoipd_msgg.h"

#define FIFO_NODEC       "/tmp/hdoipd0.cmd"
#define FIFO_NODER       "/tmp/hdoipd0.rsp"

/** Initializes the status module */
void
init_status(void)
{
    static oid systemState_oid[] = { 1,3,6,1,4,1,1111,1,1,1 };
    static oid systemUpdate_oid[] = { 1,3,6,1,4,1,1111,1,1,2 };
    static oid daemonDriver_oid[] = { 1,3,6,1,4,1,1111,1,1,3 };
    static oid daemonState_oid[] = { 1,3,6,1,4,1,1111,1,1,4 };
    static oid daemonVtbState_oid[] = { 1,3,6,1,4,1,1111,1,1,5 };
    static oid daemonVrbState_oid[] = { 1,3,6,1,4,1,1111,1,1,6 };
    static oid daemonRscState_oid[] = { 1,3,6,1,4,1,1111,1,1,7 };
    static oid ethStatus_oid[] = { 1,3,6,1,4,1,1111,1,1,8 };
    static oid vsoStatus_oid[] = { 1,3,6,1,4,1,1111,1,1,9 };
    static oid vioStatus_oid[] = { 1,3,6,1,4,1,1111,1,1,10 };
    static oid asoStatus_oid[] = { 1,3,6,1,4,1,1111,1,1,11 };
    static oid syncDelay_oid[] = { 1,3,6,1,4,1,1111,1,1,12 };
    static oid streamState_oid[] = { 1,3,6,1,4,1,1111,1,1,13 };
    static oid multicast_oid[] = { 1,3,6,1,4,1,1111,1,1,14 };
    static oid vrbIsPlaying_oid[] = { 1,3,6,1,4,1,1111,1,1,15 };
    static oid hdcpStatus_oid[] = { 1,3,6,1,4,1,1111,1,1,16 };

  DEBUGMSGTL(("status", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("systemState", handle_systemState,
                               systemState_oid, OID_LENGTH(systemState_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("systemUpdate", handle_systemUpdate,
                               systemUpdate_oid, OID_LENGTH(systemUpdate_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("daemonDriver", handle_daemonDriver,
                               daemonDriver_oid, OID_LENGTH(daemonDriver_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("daemonState", handle_daemonState,
                               daemonState_oid, OID_LENGTH(daemonState_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("daemonVtbState", handle_daemonVtbState,
                               daemonVtbState_oid, OID_LENGTH(daemonVtbState_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("daemonVrbState", handle_daemonVrbState,
                               daemonVrbState_oid, OID_LENGTH(daemonVrbState_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("daemonRscState", handle_daemonRscState,
                               daemonRscState_oid, OID_LENGTH(daemonRscState_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("ethStatus", handle_ethStatus,
                               ethStatus_oid, OID_LENGTH(ethStatus_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("vsoStatus", handle_vsoStatus,
                               vsoStatus_oid, OID_LENGTH(vsoStatus_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("vioStatus", handle_vioStatus,
                               vioStatus_oid, OID_LENGTH(vioStatus_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("asoStatus", handle_asoStatus,
                               asoStatus_oid, OID_LENGTH(asoStatus_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("syncDelay", handle_syncDelay,
                               syncDelay_oid, OID_LENGTH(syncDelay_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("streamState", handle_streamState,
                               streamState_oid, OID_LENGTH(streamState_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("multicast", handle_multicast,
                               multicast_oid, OID_LENGTH(multicast_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("vrbIsPlaying", handle_vrbIsPlaying,
                               vrbIsPlaying_oid, OID_LENGTH(vrbIsPlaying_oid),
                               HANDLER_CAN_RONLY
        ));
    netsnmp_register_scalar(
        netsnmp_create_handler_registration("hdcpStatus", handle_hdcpStatus,
                               hdcpStatus_oid, OID_LENGTH(hdcpStatus_oid),
                               HANDLER_CAN_RONLY
        ));
}

// get value generic function **************************************************

int get_value_generic(char* para, int mode, netsnmp_request_info *requests){

    int fd = -1, fdr = -1;
    char* s;
    
    // open pipe to hdoipd and check if it was successful
    fd = open(FIFO_NODEC, O_RDWR, 0600); 
    if(fd == -1) {
        snmp_log(LOG_ERR, "Failed to open (fd) %s: %s \n", FIFO_NODEC, strerror(errno));
        return -1;
    }
    
    // open pipe to hdoipd and check if it was successful
    fdr = open(FIFO_NODER, O_RDWR, 0600);
    if(fdr == -1) {
        snmp_log(LOG_ERR, "Failed to open (fdr) %s: %s \n", FIFO_NODEC, strerror(errno));
        close(fd); //close the previous pipe
        return -1;
    }
    
    switch(mode) {
        case MODE_GET:     
            s = hoic_get_param(fd, fdr, para);
            snmp_set_var_typed_value(requests->requestvb, ASN_OCTET_STR, (u_char *)s, strlen((char *)s));
            free(s);
            break;
        default:
            // we should never get here, so this is a really bad error
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_systemState\n", mode );
            close(fd);
            close(fdr);
            return -1;
    }
    
    close(fd);
    close(fdr);

    return 0;
}

// *****************************************************************************

// get system state ************************************************************
int handle_systemState(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "system-state"; 
    if (get_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get systemUpdate ************************************************************
int handle_systemUpdate(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "system-update"; 
    
    if (get_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get daemonDriver ************************************************************
int handle_daemonDriver(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "daemon-driver"; 
    
    if (get_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get daemonState *************************************************************
int handle_daemonState(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "daemon-state"; 
    
    if (get_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get daemonVtbState **********************************************************
int handle_daemonVtbState(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "daemon-vtb-state"; 
    
    if (get_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get daemonVrbState **********************************************************
int handle_daemonVrbState(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "daemon-vrb-state"; 

    if (get_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get daemonRscState **********************************************************
int handle_daemonRscState(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "daemon-rsc-state"; 
    
    if (get_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get ethStatus ***************************************************************
int handle_ethStatus(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "eth-status"; 
    
    if (get_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get vsoStatus ***************************************************************
int handle_vsoStatus(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "vso-status"; 
    
    if (get_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get vio-status **************************************************************
int handle_vioStatus(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "vio-status"; 
    
    if (get_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get aso-status **************************************************************
int handle_asoStatus(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "aso-status"; 
    
    if (get_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get sync-delay **************************************************************
int handle_syncDelay(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "sync-delay"; 
    
    if (get_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get stream-state ************************************************************
int handle_streamState(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "stream-state"; 
    
    if (get_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get multicast ***************************************************************
int handle_multicast(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "multicast"; 
    
    if (get_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get vrb-is-playing **********************************************************
int handle_vrbIsPlaying(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "vrb-is-playing";
    
    if (get_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

// get hdcp-status *************************************************************
int handle_hdcpStatus(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests){

    char para[] = "hdcp-status"; 
    
    if (get_value_generic(para, reqinfo->mode, requests) != 0){
        snmp_log(LOG_ERR, "Could not get parameter in (%d)\n", reqinfo->mode );
        return SNMP_ERR_GENERR;
    }

    return SNMP_ERR_NOERROR;
}

